name: wakewords

channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.4
  - pip==19.2.3

  - pip:
    - Flask
    - wave
    - numpy
    - pydub
    - pyopenssl
    - keras==2.8.0
    - tensorflow==2.8.0
    - boto3
    - librosa
    - sklearn
